version: '3'
services:
    reverseproxy:
        build: ./docker/reverseproxy
        ports:
            - "80:80"
            - "18081:18081"
        restart: "no"
            
    web:
        build: .
        ports:
            - "9000:9000"
            - "8080:80"
            - "11212:11211"
        volumes:
            - ./htdocs:/var/www/html
            - ./docker/web/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./docker/web/php.ini:/usr/local/etc/php/php.ini
            - ./docker/web/apache2.conf:/etc/apache2/apache2.conf
        #environment:
        #     XDEBUG_CONFIG: "idekey=VSCODE"
        #     VIRTUAL_HOST: "househunt"
        #     PHP_IDE_CONFIG: "serverName=Test"
        depends_on:
            - reverseproxy
        restart: "no"

    db:
        image:  mariadb
        environment:
            MYSQL_ROOT_PASSWORD: passpass
            MYSQL_DATABASE: house-hunt
        ports:
            - "13306:3306"
        #volumes:
        #    - ./docker/mariadb/datadir:/var/lib/mysql
        depends_on:
            - reverseproxy
        restart: "no"
           
    adminer:
        image: adminer
        ports:
            - "8081:8080"
        depends_on:
            - reverseproxy
        environment:
            - VIRTUAL_HOST=adminer
        restart: "no"