version: '3'
services:
    reverseproxy:
        build: ./docker/reverseproxy
        ports:
            - "80:80"
            - "18081:18081"
        restart: "no"
        depends_on:
          - web
          - adminer
          - mailcatcher
            
    web:
        build: .
        ports:
            - "9000"
            - "8080:80"
            - "11212:11211"
        volumes:
            - ./htdocs:/var/www/html
            - ./docker/web/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./docker/web/php.ini:/usr/local/etc/php/php.ini
            - ./docker/web/apache2.conf:/etc/apache2/apache2.conf
            - ./docker/web/setup-doctrine.sh:/var/www/html/setup-doctrine.sh
        environment:
            DATABASE: house_hunt
            DATABASE_TEST: house_hunt_test
            DB_PASSWORD: passpass
        #     XDEBUG_CONFIG: "idekey=VSCODE"
        #     VIRTUAL_HOST: "househunt"
        #     PHP_IDE_CONFIG: "serverName=Test"
        restart: "no"
        depends_on:
            - db
        # todo: create an entrypoint script to do stuff like starting memcached (that isn't running at the moment!)

    db:
        image:  mariadb
        environment:
            MYSQL_ROOT_PASSWORD: passpass
            MYSQL_DATABASE: house_hunt
        ports:
            - "13306:3306"
        #volumes:
        #    - ./docker/mariadb/datadir:/var/lib/mysql
        restart: "no"
           
    adminer:
        image: adminer
        ports:
            - "8081:8080"
        environment:
            - VIRTUAL_HOST=adminer
        restart: "no"
        depends_on:
            - db

    mailcatcher:
        image: schickling/mailcatcher

#######
# Selenium config

    selenium-hub:
        image: selenium/hub:3.141.59-mercury
        container_name: selenium-hub
        ports:
        - "4444:4444"

    selenium-chrome:
        image: selenium/node-chrome:3.141.59-mercury
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444